# Generated by Django 4.0.1 on 2022-04-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('messages', models.TextField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameC', models.CharField(max_length=50, null=True)),
                ('phoneC', models.IntegerField(blank=True, null=True)),
                ('emailC', models.EmailField(max_length=50, null=True)),
                ('addressC', models.CharField(max_length=50, null=True)),
                ('messagesC', models.TextField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameM', models.CharField(max_length=50, null=True)),
                ('phoneM', models.IntegerField(blank=True, null=True)),
                ('emailM', models.EmailField(max_length=50, null=True)),
                ('messagesM', models.TextField(max_length=50, null=True)),
            ],
        ),
    ]
