# Generated by Django 4.0.1 on 2022-04-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='phoneC',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='phoneM',
            field=models.IntegerField(blank=True, max_length=100, null=True),
        ),
    ]
