# Generated by Django 4.0.1 on 2022-04-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawapp', '0002_alter_appointment_phone_alter_consultant_phonec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='phoneC',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='phoneM',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
